Version 0.2.0

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -50,21 +50,20 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Start the application
-        run: docker compose up -d
+        run: docker compose -f docker-compose-tests.yml up --build -d 
 
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
+      - name: Show Newman results
+        run: |
+         sleep 25s
+         docker logs trustvpn-tests
 
-      - name: Setup Newman
-        run: npm install -g newman
-
-      - name: Initialize database
-        run:  docker exec -i trustvpn-db psql -U postgres < sql/db.sql
-
-      - name: Run Postman Collection
-        run: newman run tests/postman.json
+      - name: Check Newman Exit Code
+        run: |
+         if [ $(docker inspect trustvpn-tests --format='{{.State.ExitCode}}') -ne 0 ] 
+         then
+           echo "Newman failed."
+           exit 1
+         fi
 
       - name: Stop the application
         run: docker compose down
@@ -82,7 +81,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Log in to the Container registry
-        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: maxirmx
@@ -104,7 +103,7 @@ jobs:
             type=sha
 
       - name: Build and push Docker image
-        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
+        uses: docker/build-push-action@v5
         with:
           context: .
           file: ./Dockerfile
@@ -125,21 +124,20 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Start the application
-        run: docker compose -f docker-compose-ghrc.yml up -d
+        run: docker compose -f docker-compose-ghrc-tests.yml up --build -d 
 
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18
+      - name: Show Newman results
+        run: |
+         sleep 25s
+         docker logs trustvpn-tests
 
-      - name: Setup Newman
-        run: npm install -g newman
-
-      - name: Initialize database
-        run:  docker exec -i trustvpn-db psql -U postgres < sql/db.sql
-
-      - name: Run Postman Collection
-        run: newman run tests/postman.json
+      - name: Check Newman Exit Code
+        run: |
+         if [ $(docker inspect trustvpn-tests --format='{{.State.ExitCode}}') -ne 0 ] 
+         then
+           echo "Newman failed."
+           exit 1
+         fi
 
       - name: Stop the application
         run: docker compose down
